### ISSUE TITLE
book/project differences

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/getting-started-with-the-pico#35]
URL: /en/projects/getting-started-with-the-pico/6

Hi Colin Woods here, these instructions differ to those in the Official Book, page 55 there has this line of code button = machine.Pin(14, machine.Pin.IN), which makes the program run immediately.  I think it should say btn = machine.Pin(14, machine.Pin.IN, machine.Pin.PULL_DOWN) or even btn = Pin(14, Pin.IN, Pin.PULL_DOWN).

**Comment by libxx1** [comment]
Hey @MarcScott can you take a look at this please.

**Comment by MarcScott** [comment]
There were mistakes in the book, that have now been fixed and updated in the digital version.
Our project was always correct.
The new book updates can be seen here - https://hackspace.raspberrypi.org/books/micropython-pico
